WITH source AS (
    SELECT
        UPPER(TRIM(TICKER))     AS TICKER,
        PRICE,
        CURRENCY,
        RECORD_DATE,
        LOAD_DATETIME,
        RECORD_SOURCE
    FROM {{ ref('raw_market_data') }}
)

SELECT
    UPPER(sha256(UPPER(TRIM(CAST(TICKER AS VARCHAR))))::VARCHAR) AS HK_ASSET,
    UPPER(sha256(CONCAT_WS('||',
        COALESCE(UPPER(TRIM(CAST(PRICE AS VARCHAR))), '^^'),
        COALESCE(UPPER(TRIM(CAST(CURRENCY AS VARCHAR))), '^^')
    ))::VARCHAR) AS HASHDIFF_MARKET,
    TICKER,
    PRICE,
    CURRENCY,
    RECORD_DATE         AS EFFECTIVE_FROM,
    LOAD_DATETIME,
    RECORD_SOURCE
FROM source
