WITH source AS (
    SELECT
        UPPER(TRIM(FUND_ID))    AS FUND_ID,
        FUND_NAME,
        UPPER(TRIM(TICKER))     AS TICKER,
        SHARES_HELD,
        LOAD_DATETIME,
        RECORD_SOURCE
    FROM {{ ref('raw_fund_portfolio') }}
)

SELECT
    UPPER(sha256(UPPER(TRIM(CAST(FUND_ID AS VARCHAR))))::VARCHAR) AS HK_FUND,
    UPPER(sha256(UPPER(TRIM(CAST(TICKER AS VARCHAR))))::VARCHAR) AS HK_ASSET,
    UPPER(sha256(CONCAT_WS('||',
        COALESCE(UPPER(TRIM(CAST(FUND_ID AS VARCHAR))), '^^'),
        COALESCE(UPPER(TRIM(CAST(TICKER AS VARCHAR))), '^^')
    ))::VARCHAR) AS HK_FUND_ASSET,
    UPPER(sha256(CONCAT_WS('||',
        COALESCE(UPPER(TRIM(CAST(FUND_NAME AS VARCHAR))), '^^'),
        COALESCE(UPPER(TRIM(CAST(SHARES_HELD AS VARCHAR))), '^^')
    ))::VARCHAR) AS HASHDIFF_PORTFOLIO,
    FUND_ID,
    FUND_NAME,
    TICKER,
    SHARES_HELD,
    LOAD_DATETIME,
    RECORD_SOURCE
FROM source
